### ISSUE TITLE
似乎默认开启了英文语法检查

### ISSUE THREAD

**Issue by TigerBeanst** [lake2/wolai_desktop#1]
![image](https://user-images.githubusercontent.com/3889846/96262223-17c2a080-0ff4-11eb-82b2-2808e1478121.png)
显得有点……

**Comment by lake2** [comment]
> ![image](https://user-images.githubusercontent.com/3889846/96262223-17c2a080-0ff4-11eb-82b2-2808e1478121.png)
> 显得有点……

已修复，请下载最新版
